stages:
  - build
  - run

build job:
  stage: build
  script:
    - pip3 install -r requirements.txt
    - echo "Build stage completed successfully"

run job:
  stage: run
  script:
    - python3 app.py
    - echo "Run stage completed successfully"
